import { z } from 'zod';

/**
 * Path identifiers.
 *
 * Every identifier DevSync puts in a URL is an opaque UUID generated by the
 * persistence layer. A client never chooses one, so a malformed identifier is a
 * client that built the wrong URL rather than a lookup that happens to miss —
 * which is why it is rejected here, before any service or query runs, and
 * answered with `INVALID_IDENTIFIER` rather than a `404`.
 */

export const projectIdSchema = z.uuid();

export const fileIdSchema = z.uuid();

/** The path parameters of every `/projects/:projectId` route. */
export const projectParamsSchema = z.strictObject({
  projectId: projectIdSchema,
});

export type ProjectParams = z.infer<typeof projectParamsSchema>;

/** The path parameters of every `/projects/:projectId/files/:fileId` route. */
export const projectFileParamsSchema = z.strictObject({
  projectId: projectIdSchema,
  fileId: fileIdSchema,
});

export type ProjectFileParams = z.infer<typeof projectFileParamsSchema>;
