-- Generated by `prisma migrate dev --create-only`, with one deliberate edit:
-- `project_files.name` is pinned to the "C" collation. Prisma has no way to
-- express a collation, and the unique index below would otherwise inherit
-- whatever locale the server was initialised with — which decides whether
-- README.md and readme.md are the same file name. "C" compares byte-wise, so the
-- rule is case-sensitive and deterministic wherever this migration is applied.
-- The behaviour is covered by tests in `tests/project-files.test.ts`.

-- CreateTable
CREATE TABLE "projects" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "name" VARCHAR(100) NOT NULL,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(6) NOT NULL,

    CONSTRAINT "projects_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "project_files" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "project_id" UUID NOT NULL,
    "name" VARCHAR(255) COLLATE "C" NOT NULL,
    "language" TEXT NOT NULL,
    "content" TEXT NOT NULL,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(6) NOT NULL,

    CONSTRAINT "project_files_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "projects_updated_at_id_idx" ON "projects"("updated_at" DESC, "id" DESC);

-- CreateIndex
CREATE INDEX "project_files_project_id_created_at_id_idx" ON "project_files"("project_id", "created_at", "id");

-- CreateIndex
CREATE UNIQUE INDEX "project_files_project_id_name_key" ON "project_files"("project_id", "name");

-- AddForeignKey
ALTER TABLE "project_files" ADD CONSTRAINT "project_files_project_id_fkey" FOREIGN KEY ("project_id") REFERENCES "projects"("id") ON DELETE CASCADE ON UPDATE CASCADE;
